server:
  port: 8098


spring:
  application:
    name: report-service



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.97.43:8761/eureka